apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-zhwg-topo
  labels:
    app: service-zhwg-topo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-zhwg-topo
  template:
    metadata:
      labels:
        app: service-zhwg-topo
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec: 
      containers:
      - name: app
        image: IMAGENAME:latest
        imagePullPolicy: Always
        args:
        - --server.port=80
        - --spring.application.name=service-zhwg-topo
        - --eureka.instance.prefer-ip-address=true
        - --eureka.instance.ip-address=10.15.2.170
        - --eureka.instance.hostname=10.15.2.170
        - --eureka.instance.nonSecurePort=21010
        - --eureka.instance.instance-id=${eureka.instance.ip-address}:${eureka.instance.nonSecurePort}
        - --eureka.client.serviceUrl.defaultZone=http://admin:1@10.15.2.170:21001/eureka/
        ports:
        - containerPort: 80
        env:
        - name: TZ
          value: "Asia/Shanghai"
        resources:
          requests:
            memory: 256Mi
          limits:
            memory: 4096Mi
