tm_get_topo: /restconf/data/sptn-net-topology:net-topology/topologies?layer-rate=2
tm_get_point_topo: /restconf/data/sptn-net-topology:net-topology/topologies/topology=
tm_get_topo_intne: /restconf/data/sptn-net-topology:net-topology/nodes?parent-topo-id=
tm_get_uuid_ne: /restconf/data/sptn-net-topology:net-topology/nodes
tm_get_intne: /restconf/data/sptn-net-topology:net-topology/nodes/node=
tm_get_topo_extne: /restconf/data/sptn-net-topology:net-topology/ext-nodes?parent-topo-id=
tm_get_extne: /restconf/data/sptn-net-topology:net-topology/ext-nodes/ext-node=
tm_get_topo_intlink: /restconf/data/sptn-net-topology:net-topology/links?parent-topo-id=
tm_get_uuid_link: /restconf/data/sptn-net-topology:net-topology/links
tm_get_intlink: /restconf/data/sptn-net-topology:net-topology/links/link=
tm_get_intlink_st: /restconf/data/sptn-net-topology:net-topology/links/link=
tm_get_topo_extlink: /restconf/data/sptn-net-topology:net-topology/ext-links?parent-topo-id=
tm_get_ext_link: /restconf/data/sptn-net-topology:net-topology/ext-links/ext-link=
tm_get_extlink_st: /restconf/data/sptn-net-topology:net-topology/ext-links/ext-link=
tm_create_extlink: /restconf/data/sptn-net-topology:net-topology/ext-links
tm_del_extlink: /restconf/data/sptn-net-topology:net-topology/ext-links/ext-link=
#
tm_create_link_te: /restconf/data/sptn-net-topology:net-topology/links/link=?/link-te-attr-cfg
rm_get_ncd_ne: /restconf/data/sptn-resources-module:resources/nes?ncd-id=
rm_get_uuid_ne: /restconf/data/sptn-resources-module:resources/nes
rm_get_ne: /restconf/data/sptn-resources-module:resources/nes/ne-list/ne=
#
rm_get_ne_port: /restconf/data/sptn-resources-module:resources/nes/ne-list/ne=/ltps
rm_get_ncd: /restconf/data/sptn-resources-module:resources/ncd-list/ncd=
rm_get_con_ncd: /restconf/data/sptn-resources-module:resources/ncd-list
rm_get_con_all_ncd: /restconf/operations/sptn-resources-module:get-all-ncds
rm_get_ncd_to_ncd: /restconf/operations/sptn-resources-module:get-specified-ncd
rm_get_res_fdn: /restconf/operations/sptn-uuid-fdnmodule:get-id-fdnmapping
rm_get_fdn_res: /restconf/operations/sptn-uuid-fdnmodule:get-fdn-idmapping
rm_get_uuid: /restconf/data/sptn-uuid-module:get-uuid?res-type=ne
rm_get_uuid_to_rmuid: /restconf/operations/sptn-uuid-rmuid-module:get-id-rmuid-mapping
rm_get_rmuid_to_uuid: /restconf/operations/sptn-uuid-rmuid-module:get-rmuid-id-mapping
tum_get_tunnel: /restconf/data/sptn-service-tunnel:service/snc-tunnels?depth=1
tum_get_uuid_tunnel: /restconf/data/sptn-service-tunnel:service/snc-tunnels
tum_get_point_tunnel: /restconf/data/sptn-service-tunnel:service/snc-tunnels/snc-tunnel=
tum_get_lsp_route: /restconf/data/sptn-service-route:service/snc-routes/snc-route?snc-id=
tum_get_uuid_lsproute: /restconf/data/sptn-service-route:service/snc-routes/snc-route
tum_create_tunnel: /restconf/operations/sptn-service-tunnel:create-tunnel
tum_del_tunnel: /restconf/operations/sptn-service-tunnel:delete-tunnel
tum_modify_tunnel: /restconf/data/sptn-service-tunnel:service/snc-tunnels/snc-tunnel=id
#
tum_modify_tunnel_qos: /restconf/data/sptn-service-tunnel:service/snc-tunnels/snc-tunnel=?/qos
#
tum_modify_tunnel_snc: /restconf/data/sptn-service-tunnel:service/snc-tunnels/snc-tunnel=?/snc-switch
tum_create_lsp: /restconf/operations/sptn-service-tunnel:create-lsp
#
tum_modify_lsp_oam: /restconf/data/sptn-service-tunnel:service/snc-tunnels/snc-tunnel=id/snc-lsps/snc-lsp=?/oam
tum_del_lsp: /restconf/operations/sptn-service-tunnel:delete-lsp
tum_modify_lsp_snc: /restconf/data/sptn-service-route:service/snc-routes/snc-route?snc-lsp-id=
tum_cou_route: /restconf/operations/sptn-service-route:request-reoptimize-routes
tum_down_route: /restconf/operations/sptn-service-tunnel:reoptimize-lsp
se_get_eline: /restconf/data/sptn-service-eline:service/snc-elines?depth=1
se_get_uuid_eline: /restconf/data/sptn-service-eline:service/snc-elines
se_get_point_eline: /restconf/data/sptn-service-eline:service/snc-elines/snc-eline=
se_create_eline: /restconf/operations/sptn-service-eline:create-snc-eline
se_del_eline: /restconf/operations/sptn-service-eline:delete-snc-eline
se_mod_eline: /restconf/data/sptn-service-eline:service/snc-elines/snc-eline=
se_mod_pw_qos: /restconf/data/sptn-service-eline:service/snc-elines/snc-eline=id/snc-pws/snc-pw=
#
se_mod_in_ep_qos: /restconf/data/sptn-service-eline:service/snc-elines/snc-eline=id/snc-pws/snc-pw=?/qos
se_mod_out_ep_qos: /restconf/data/sptn-service-eline:service/snc-elines/snc-eline=id/ingress-end-points/ingress-end-point=?,?/qos
se_mod_pw: /restconf/data/sptn-service-eline:service/snc-elines/snc-eline=id/egress-end-points/egress-end-point=id1,ltpid2/qos
se_mod_in_ep: /restconf/data/sptn-service-eline:service/snc-elines/snc-eline=id/ingress-end-points/ingress-end-point=id1,ltpid2
se_mod_out_ep: /restconf/data/sptn-service-eline:service/snc-elines/snc-eline=id/egress-end-points/egress-end-point=id1,ltpid2

rpc_route: /restconf/operations/sptn-service-route:request-routes
rpc_dou_route: /restconf/operations/sptn-service-route:request-restore-routes
rpc_lsp_route: /restconf/operations/sptn-service-tunnel:reroute
rpc_lsp_dou_route: /restconf/operations/sptn-service-tunnel:restore-lsp
rpc_get_meg_id: /restconf/operations/sptn-service-tunnel:request-megid-spaces
rpc_get_vlan_id: /restconf/operations/sptn-service-eline:request-vlanid-spaces
rpc_get_pw_vcid: /restconf/operations/sptn-service-eline:request-vcid-spaces
rpc_get_ne_lab: /restconf/operations/sptn-service-tunnel:request-labels
rpc_get_alm: /restconf/data/sptn-service-alarm:service/current-alarm
rpc_get_pal: /restconf/operations/do-heartbeat-hmf-controller
snc_get_l3vpn: /restconf/data/sptn-c2c-service-l3vpn:service/snc-l3vpns
snc_create_l3vpn: /restconf/data/sptn-c2c-service-l3vpn:service/snc-l3vpns
snc_del_l3vpn: /restconf/data/sptn-c2c-service-l3vpn:service/snc-l3vpns/snc-l3vpn=
snc_mod_l3vpn: /restconf/data/sptn-c2c-service-l3vpn:service/snc-l3vpns/snc-l3vpn=
snc_add_l3vpn_ac_port: /restconf/data/sptn-c2c-service-l3vpn:service/snc-l3vpns/snc-l3vpn=id/acs
snc_del_l3vpn_ac_port: /restconf/data/sptn-c2c-service-l3vpn:service/snc-l3vpns/snc-l3vpn=id/acs/ac=
snc_mod_l3vpn_ac_qos: /restconf/data/sptn-c2c-service-l3vpn:service/snc-l3vpns/snc-l3vpn=id/acs/ac=
snc_add_l3vpn_rel: /restconf/data/sptn-c2c-service-l3vpn:service/snc-l3vpns/snc-l3vpn=id/bind-relation-list
snc_del_l3vpn_rel: /restconf/data/sptn-c2c-service-l3vpn:service/snc-l3vpns/snc-l3vpn=id/bind-relation-list/l3-bind-relation=
snc_mod_l3vpn_rel: /restconf/data/sptn-c2c-service-l3vpn:service/snc-l3vpns/snc-l3vpn=id/bind-relation-list/l3-bind-relation=
snc_add_static_route: /restconf/data/sptn-c2c-service-l3vpn:service/snc-l3vpns/snc-l3vpn=id/acs/protocol-list/static-routes
snc_del_static_route: /restconf/operations/sptn-c2c-service-l3vpn:delete-routes
snc_issue_static_route: /restconf/operations/sptn-c2c-service-l3vpn:redistribute-routes
l2l3_get_gateway: /restconf/data/sptn-c2c-service-l2l3-gateway:service/l2l3-gateways
l2l4_get_l2ve_port: /restconf/operations/sptn-c2c-service-l2l3-gateway:request-l2ve
l2l3_create_gateway: /restconf/data/sptn-c2c-service-l2l3-gateway:service/l2l3-gateways
l2l3_del_gateway: /restconf/data/sptn-c2c-service-l2l3-gateway:service/l2l3-gateways/l2l3-gateway=
l2l3_mod_gateway: /restconf/data/sptn-c2c-service-l2l3-gateway:service/l2l3-gateways/l2l3-gateway=
perform_get_history_data: /restconf/operations/sptn-pm-module:history-query
perform_get_data: /restconf/operations/sptn-service-pm:request-traffic-checkpoints
perform_open_monitor: /restconf/operations/sptn-service-pm:set-status-traffic-checkpoints
to_create_access_token: /controller/v2/tokens
to_create_get_token: /restconf/operations/huawei-ac-access-token:get-token
to_create_deltoken: /restconf/operations/huawei-ac-access-token:revoke-token
to_system_monitor: /restconf/operational/ietf-system:system-state/
